language: node_js
node_js:
- '5'
env:
- NODE_ENV=TEST CXX=g++-4.8
services:
- postgresql
addons:
  postgresql: '9.4'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- psql -c 'create database expenses;' -U postgres
- sleep 15
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run build
- travis_retry npm run lint
- travis_retry npm test
deploy:
  provider: heroku
  api_key:
    secure: j5Woa9I5xsB4hr59VDXFmwSHdxkHR2nWFezMk3BJuAVAI2hPTgyEx1on+f0op8nyplIMIXdxp5JhTRmSCyi3pwI3uL1JC4J7wOWtXPhG3zLpv95MwN3DctJKyOJtGdQe6/cgxxBViJhY4oyK/rdHl4NvQOyADN3KIBRSO1PM/1aCaoy35GCTARymM4J/KrDdiWkfJqg0Y18mUts2vPU0aUvd+F9SqMhDeZJ5MbYMBXqDoAPCwablhO2CVVrdioF82h0MT0RvT0nGpSxM/0akxJkma36SWNKcrwF37KHwxtDNcEpnnjRk9nJMH14tzdvxqFjHyfjQxVJ82aXWBxzdViJNm2leJfoiZGocVPxW4hzuOaAnM2jJyMx9JxyPld3GvdYcmCbv4hiEUeBM2UtRFgI5tn2DcWfYiMWv/fHNrURiBUNFShZZO5FlDUBM26GA3YDDt8rtVPGcbHKo2W0gxgyd+UAHqMZ4TI8L75akXWbLpOCJVOZbhBCS2pZvKvzEzYhw/MYytvHXbq+Zz7OHiYNlRnUWfSQfc2EvmPitnOhBmqttI7PzFUtADlSMciMyJo/RbBVCW/+gxlAPVvAJWlJS46oTmye0DZtMpSyeLLDEkNAeJy/DnL6/UY7jXxiilhrvuQDhF4M3JCkf726CP0NMAyCAfkncB1hCiQiNF7w=
  app: calm-reef-93989
  on:
    repo: jseminck/jseminck-be-api-expenses
  skip_cleanup: true
